### ISSUE TITLE
Cant run the code

### ISSUE THREAD

**Issue by alexibar101** [Dono27/rock-paper-scissors#2]
Im trying to run the program but its not executing.....sorry i am new to coding

**Comment by bencevarga666** [comment]
It is a Python3 source code, so you need to run interactively with a Python interpreter. You can download it for various platforms from: [https://www.python.org/downloads/](https://www.python.org/downloads/)

After the installation process, you should be able to run this code with the `python rockpaperscissors.py` or with the `python3 rockpaperscissors.py` command.

If you have a different kind of problem, please, paste the error message below.
